services:
  backend:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      TZ: UTC
      PGTZ: UTC

  configurator:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: "no"
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
      TZ: UTC
      PGTZ: UTC
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: "no"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --install-app hrms --install-app payments --install-app cheese --set-default frontend;
    environment:
      TZ: UTC
      PGTZ: UTC

  db:
    image: mariadb:10.11
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      TZ: UTC
      PGTZ: UTC
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    depends_on:
      - websocket
    restart: unless-stopped
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
      TZ: UTC
      PGTZ: UTC
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "127.0.0.1:8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=websecure
      - traefik.http.routers.frontend-http.tls.certresolver=main-resolver
      - traefik.http.routers.frontend-http.rule=${SITES_RULE:-Host(`localhost`)}

  queue-long:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: unless-stopped
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
      TZ: UTC
      PGTZ: UTC

  queue-short:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: unless-stopped
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
      TZ: UTC
      PGTZ: UTC

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

  scheduler:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: unless-stopped
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs
    environment:
      TZ: UTC
      PGTZ: UTC

  websocket:
    image: ghcr.io/deepzide/cheese:${TAG:-latest}
    networks:
      - frappe_network
    restart: unless-stopped
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
      TZ: UTC
      PGTZ: UTC
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - sites-assets:/home/frappe/frappe-bench/sites/assets
      - logs:/home/frappe/frappe-bench/logs

  alloy:
    image: grafana/alloy:latest
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - logs:/var/log/frappe:ro
      - /opt/erpnext/alloy-config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-staging}

  proxy:
    image: traefik:v3.6
    networks:
      - frappe_network
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frappe_network
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesResolvers.main-resolver.acme.httpChallenge=true
      - --certificatesResolvers.main-resolver.acme.httpChallenge.entrypoint=web
      - --certificatesResolvers.main-resolver.acme.email=${LETSENCRYPT_EMAIL:-admin@example.com}
      - --certificatesResolvers.main-resolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  cert-data:
  db-data:
  redis-queue-data:
  sites:
  sites-assets:
  logs:

networks:
  frappe_network:
    driver: bridge
