FROM cheese-base:version-15 AS builder

COPY . /home/frappe/frappe-bench/apps/cheese

USER frappe
RUN cd /home/frappe/frappe-bench/apps/cheese \
    && /home/frappe/frappe-bench/env/bin/pip install --no-deps -e .

FROM frappe/base:version-15

USER frappe
COPY --from=builder /home/frappe/frappe-bench /home/frappe/frappe-bench

VOLUME ["/home/frappe/frappe-bench/sites", "/home/frappe/frappe-bench/sites/assets", "/home/frappe/frappe-bench/logs"]

WORKDIR /home/frappe/frappe-bench

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]
